version: 2.1

jobs:
  run-lint:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - save_cache:
          paths: [./venv]
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get ugrade
            sudo apt-get install wget
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            sudo apt-get install python3
            make setup
            . venv/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
workflows:
  default:
    jobs:
        - run-lint