version: 2.1

jobs:
  run-lint:
    docker:
      - image: python:3.8-slim
    steps:
      - checkout
      - restore_cache:
          keys: [v1-dependencies-{{ checksum "requirements.txt" }}]
      - save_cache:
          paths: [./venv]
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
workflows:
  default:
    jobs:
        - run-lint