version: 2.1

jobs:
  run-lint:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - save_cache:
          paths: [./venv]
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            apt-get update -y
            apt-get upgrade -y
            apt-get install wget -y
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            apt-get install python3 python3-venv -y
            apt-get install make -y
            make setup
            . venv/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            . ./.venv/bin/activate
            make lint
            
workflows:
  default:
    jobs:
        - run-lint